---
- name: Install ECS container agent
  ansible.builtin.yum:
    name: ecs-init
    state: present

- name: Deploy ECS agent configuration
  ansible.builtin.template:
    src: ecs.config.j2
    dest: /etc/ecs/ecs.config
    owner: root
    group: root
    mode: "0600"
  notify: Restart ECS agent

- name: Start and enable ECS agent
  ansible.builtin.systemd:
    name: ecs
    state: started
    enabled: true
